[toolchain]
package_manager = "yarn"

[features]
seeds = false
skip-lint = false
resolution = true

[programs.localnet]
verity = "2pw3GT51qRHmrobvzmBzso2iHCBv5rN8MTNTNMxEyG2P"

[programs.devnet]
verity = "2pw3GT51qRHmrobvzmBzso2iHCBv5rN8MTNTNMxEyG2P"

[programs.mainnet]
verity = "2pw3GT51qRHmrobvzmBzso2iHCBv5rN8MTNTNMxEyG2P"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

